// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv0EaIBxkcluwOGPL7eGMnepRQe1LDqvw',
    appId: '1:417722456480:web:b3e7d5f339855b2677acc5',
    messagingSenderId: '417722456480',
    projectId: 'flutter-firebase-conect-first',
    authDomain: 'flutter-firebase-conect-first.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-conect-first-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-conect-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoCtTKGP4xVQO-pNBtBOV2bVQi8IUmwiw',
    appId: '1:417722456480:android:9794ecb1e063e38377acc5',
    messagingSenderId: '417722456480',
    projectId: 'flutter-firebase-conect-first',
    databaseURL: 'https://flutter-firebase-conect-first-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-conect-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCumL5ISAvJCgnuggv5Jt3Y2DVkBkvTywo',
    appId: '1:417722456480:ios:7bd41d6650b66a1177acc5',
    messagingSenderId: '417722456480',
    projectId: 'flutter-firebase-conect-first',
    databaseURL: 'https://flutter-firebase-conect-first-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-conect-first.appspot.com',
    iosClientId: '417722456480-653misa5dnje1s4g0rqtvn8nl2tgk53h.apps.googleusercontent.com',
    iosBundleId: 'com.example.boseyoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCumL5ISAvJCgnuggv5Jt3Y2DVkBkvTywo',
    appId: '1:417722456480:ios:7bd41d6650b66a1177acc5',
    messagingSenderId: '417722456480',
    projectId: 'flutter-firebase-conect-first',
    databaseURL: 'https://flutter-firebase-conect-first-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-conect-first.appspot.com',
    iosClientId: '417722456480-653misa5dnje1s4g0rqtvn8nl2tgk53h.apps.googleusercontent.com',
    iosBundleId: 'com.example.boseyoProject',
  );
}
